# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.3
  - 2.7
  - 2.6

env:
  matrix:
  - DJANGO='django>=1.4,<1.5'
  - DJANGO='django>=1.5,<1.6'
  - DJANGO='django>=1.6,<1.7'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt
  - pip install python-coveralls coverage

# command to run tests, e.g. python setup.py test
script: coverage run runtests.py

after_success: coveralls

matrix:
  exclude:
  - python: 3.3
    env: DJANGO='django>=1.4,<1.5'

  allow_failures:
    - python: 3.3
      env: DJANGO='django>=1.5,<1.6'
    - python: 3.3
      env: DJANGO='django>=1.6,<1.7'
