# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings

DEFAULT_THEMES = (
    ('arta', 'Arta'),
    ('ascetic', 'Ascetic'),
    ('atelier-dune.dark', 'Atelier Dune - Dark'),
    ('atelier-dune.light', 'Atelier Dune - Light'),
    ('atelier-forest.dark', 'Atelier forest - Dark'),
    ('atelier-forest.light', 'Atelier forest - Light'),
    ('atelier-heath.dark', 'Atelier heath - Dark'),
    ('atelier-heath.light', 'Atelier heath - Light'),
    ('atelier-lakeside.dark', 'Atelier lakeside - Dark'),
    ('atelier-lakeside.light', 'Atelier lakeside - Light'),
    ('atelier-seaside.dark', 'Atelier seaside - Dark'),
    ('atelier-seaside.light', 'Atelier seaside - Light'),
    ('brown_paper', 'Brown Paper'),
    ('dark', 'Dark'),
    ('default', 'Default'),
    ('docco', 'Docco'),
    ('far', 'Far'),
    ('foundation', 'Foundation'),
    ('github', 'Github'),
    ('googlecode', 'GoogleCode'),
    ('idea', 'IDEA'),
    ('ir_black', 'Ir black'),
    ('magula', 'Magula'),
    ('mono-blue', 'Mono Blue'),
    ('monokai', 'Monokai'),
    ('monokai_sublime', 'Monokai sublime'),
    ('obsidian', 'Obsidian'),
    ('paraiso.dark', 'Paraiso - Dark'),
    ('paraiso.light', 'éaraiso - Light'),
    ('pojoaque', 'Pojoaque'),
    ('railscasts', 'RailsCasts'),
    ('rainbow', 'Rainbow'),
    ('school_book', 'School Book'),
    ('solarized_dark', 'Solarized - Dark'),
    ('solarized_light', 'Solarized - Light'),
    ('sunburst', 'Sunburst'),
    ('tomorrow', 'Tomorrow'),
    ('tomorrow-night-blue', 'Tomorrow night - Blug'),
    ('tomorrow-night-bright', 'Tomorrow night - Bright'),
    ('tomorrow-night', 'Tomorrow night'),
    ('tomorrow-night-eighties', 'Tomorrow night - Eighties'),
    ('vs', 'VS'),
    ('xcode', 'XCode'),
    ('zenburn', 'Zenburn'),
)

HIGHLIGHT_THEMES = getattr(settings, 'HIGHLIGHT_THEMES', DEFAULT_THEMES)

DEFAULT_LANGUAGES = (
    ('1C', '1c'),
    ('Access logs', 'accesslog'),
    ('Ada', 'ada'),
    ('ARM assembler', 'armasm', 'arm'),
    ('AVR assembler', 'avrasm'),
    ('ActionScript', 'actionscript', 'as'),
    ('Apache', 'apache', 'apacheconf'),
    ('AppleScript', 'applescript', 'osascript'),
    ('AsciiDoc', 'asciidoc', 'adoc'),
    ('AspectJ', 'aspectj'),
    ('AutoHotkey', 'autohotkey'),
    ('AutoIt', 'autoit'),
    ('Axapta', 'axapta'),
    ('Bash', 'bash', 'sh', 'zsh'),
    ('Basic', 'basic'),
    ('BNF', 'bnf'),
    ('Brainfuck', 'brainfuck', 'bf'),
    ('C#', 'cs', 'csharp'),
    ('C++', 'cpp', 'c', 'cc', 'h', 'c++', 'h++', 'hpp'),
    ('C/AL', 'cal'),
    ('Cache Object Script', 'cos', 'cls'),
    ('CMake', 'cmake', 'cmake.in'),
    ('CSP', 'csp'),
    ('CSS', 'css'),
    ('Cap’n Proto', 'capnproto', 'capnp'),
    ('Clojure', 'clojure', 'clj'),
    ('CoffeeScript', 'coffeescript', 'coffee', 'cson', 'iced'),
    ('Crmsh', 'crmsh', 'crm', 'pcmk'),
    ('Crystal', 'crystal', 'cr'),
    ('D', 'd'),
    ('DNS Zone file', 'dns', 'zone', 'bind'),
    ('DOS', 'dos', 'bat', 'cmd'),
    ('Dart', 'dart'),
    ('Delphi', 'delphi', 'dpr', 'dfm', 'pas', 'pascal', 'freepascal',
     'lazarus', 'lpr', 'lfm'),
    ('Diff', 'diff', 'patch'),
    ('Django', 'django', 'jinja'),
    ('Dockerfile', 'dockerfile', 'docker'),
    ('DTS (Device Tree', 'dts'),
    ('Dust', 'dust', 'dst'),
    ('Elixir', 'elixir'),
    ('Elm', 'elm'),
    ('Erlang', 'erlang', 'erl'),
    ('F#', 'fsharp', 'fs'),
    ('FIX', 'fix'),
    ('Fortran', 'fortran', 'f90', 'f95'),
    ('G-Code', 'gcode', 'nc'),
    ('Gams', 'gams', 'gms'),
    ('GAUSS', 'gauss', 'gss'),
    ('Gherkin', 'gherkin'),
    ('Go', 'go', 'golang'),
    ('Golo', 'golo', 'gololang'),
    ('Gradle', 'gradle'),
    ('Groovy', 'groovy'),
    ('HTML,XML', 'xml', 'html', 'xhtml', 'rss', 'atom', 'xjb', 'xsd', 'xsl',
     'plist'),
    ('HTTP', 'http', 'https'),
    ('Haml', 'haml'),
    ('Handlebars', 'handlebars', 'hbs', 'html.hbs', 'html.handlebars'),
    ('Haskell', 'haskell', 'hs'),
    ('Haxe', 'haxe', 'hx'),
    ('Ini', 'ini'),
    ('Inform7', 'inform7', 'i7'),
    ('IRPF90', 'irpf90'),
    ('JSON', 'json'),
    ('Java', 'java', 'jsp'),
    ('JavaScript', 'javascript', 'js', 'jsx'),
    ('Lasso', 'lasso', 'ls', 'lassoscript'),
    ('Less', 'less'),
    ('Lisp', 'lisp'),
    ('LiveCode Server', 'livecodeserver'),
    ('LiveScript', 'livescript', 'ls'),
    ('Lua', 'lua'),
    ('Makefile', 'makefile', 'mk', 'mak'),
    ('Markdown', 'markdown', 'md', 'mkdown', 'mkd'),
    ('Mathematica', 'mathematica', 'mma'),
    ('Matlab', 'matlab'),
    ('Maxima', 'maxima'),
    ('Maya Embedded Language', 'mel'),
    ('Mercury', 'mercury'),
    ('Mizar', 'mizar'),
    ('Mojolicious', 'mojolicious'),
    ('Monkey', 'monkey'),
    ('Moonscript', 'moonscript', 'moon'),
    ('NSIS', 'nsis'),
    ('Nginx', 'nginx', 'nginxconf'),
    ('Nimrod', 'nimrod', 'nim'),
    ('Nix', 'nix'),
    ('OCaml', 'ocaml', 'ml'),
    ('Objective', 'C', 'objectivec', 'mm', 'objc', 'obj-c'),
    ('OpenGL Shading Language', 'glsl'),
    ('OpenSCAD', 'openscad', 'scad'),
    ('Oracle Rules Language', 'ruleslanguage'),
    ('Oxygene', 'oxygene'),
    ('PF', 'pf', 'pf.conf'),
    ('PHP', 'php', 'php3', 'php4', 'php5', 'php6'),
    ('Parser3', 'parser3'),
    ('Perl', 'perl', 'pl', 'pm'),
    ('PowerShell', 'powershell', 'ps'),
    ('Processing', 'processing'),
    ('Prolog', 'prolog'),
    ('Protocol Buffers', 'protobuf'),
    ('Puppet', 'puppet', 'pp'),
    ('Python', 'python', 'py', 'gyp'),
    ('Python profiler results', 'profile'),
    ('Q', 'k', 'kdb'),
    ('QML', 'qml'),
    ('R', 'r'),
    ('RenderMan RIB', 'rib'),
    ('RenderMan RSL', 'rsl'),
    ('Roboconf', 'graph', 'instances'),
    ('Ruby', 'ruby', 'rb', 'gemspec', 'podspec', 'thor', 'irb'),
    ('Rust', 'rust', 'rs'),
    ('SCSS', 'scss'),
    ('SQL', 'sql'),
    ('STEP Part 21', 'p21', 'step', 'stp'),
    ('Scala', 'scala'),
    ('Scheme', 'scheme'),
    ('Scilab', 'scilab', 'sci'),
    ('Smali', 'smali'),
    ('Smalltalk', 'smalltalk', 'st'),
    ('Stan', 'stan'),
    ('Stata', 'stata'),
    ('Stylus', 'stylus', 'styl'),
    ('Swift', 'swift'),
    ('Tcl', 'tcl', 'tk'),
    ('TeX', 'tex'),
    ('Thrift', 'thrift'),
    ('TP', 'tp'),
    ('Twig', 'twig', 'craftcms'),
    ('TypeScript', 'typescript', 'ts'),
    ('VB.Net', 'vbnet', 'vb'),
    ('VBScript', 'vbscript', 'vbs'),
    ('VHDL', 'vhdl'),
    ('Vala', 'vala'),
    ('Verilog', 'verilog', 'v'),
    ('Vim', 'Script', 'vim'),
    ('x86 Assembly', 'x86asm'),
    ('XL', 'xl', 'tao'),
    ('XQuery', 'xpath', 'xq'),
    ('Zephir', 'zephir', 'zep'),
)

HIGHLIGHT_LANGUAGES = getattr(settings, 'HIGHLIGHT_LANGUAGES',
                              DEFAULT_LANGUAGES)
