# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf import settings

DEFAULT_THEMES = (
    ('a11y-dark', 'A 11 Y Dark'),
    ('a11y-light', 'A 11 Y Light'),
    ('agate', 'Agate'),
    ('androidstudio', 'An Old Hope'),
    ('an-old-hope', 'Androidstudio'),
    ('arduino-light', 'Arduino Light'),
    ('arta', 'Arta'),
    ('ascetic', 'Ascetic'),
    ('atelier-cave-dark', 'Atelier Cave Dark'),
    ('atelier-cave-light', 'Atelier Cave Light'),
    ('atelier-dune-dark', 'Atelier Dune Dark'),
    ('atelier-dune-light', 'Atelier Dune Light'),
    ('atelier-estuary-dark', 'Atelier Estuary Dark'),
    ('atelier-estuary-light', 'Atelier Estuary Light'),
    ('atelier-forest-dark', 'Atelier Forest Dark'),
    ('atelier-forest-light', 'Atelier Forest Light'),
    ('atelier-heath-dark', 'Atelier Heath Dark'),
    ('atelier-heath-light', 'Atelier Heath Light'),
    ('atelier-lakeside-dark', 'Atelier Lakeside Dark'),
    ('atelier-lakeside-light', 'Atelier Lakeside Light'),
    ('atelier-plateau-dark', 'Atelier Plateau Dark'),
    ('atelier-plateau-light', 'Atelier Plateau Light'),
    ('atelier-savanna-dark', 'Atelier Savanna Dark'),
    ('atelier-savanna-light', 'Atelier Savanna Light'),
    ('atelier-seaside-dark', 'Atelier Seaside Dark'),
    ('atelier-seaside-light', 'Atelier Seaside Light'),
    ('atelier-sulphurpool-dark', 'Atelier Sulphurpool Dark'),
    ('atelier-sulphurpool-light', 'Atelier Sulphurpool Light'),
    ('atom-one-dark-reasonable', 'Atom One Dark Reasonable'),
    ('atom-one-dark', 'Atom One Dark'),
    ('atom-one-light', 'Atom One Light'),
    ('brown-paper', 'Brown Paper'),
    ('codepen-embed', 'Codepen Embed'),
    ('color-brewer', 'Color Brewer'),
    ('darcula', 'Darcula'),
    ('dark', 'Dark'),
    ('darkula', 'Darkula'),
    ('docco', 'Docco'),
    ('dracula', 'Dracula'),
    ('far', 'Far'),
    ('foundation', 'Foundation'),
    ('github', 'Github Gist'),
    ('github-gist', 'Github'),
    ('gml', 'Gml'),
    ('googlecode', 'Googlecode'),
    ('grayscale', 'Grayscale'),
    ('gruvbox-dark', 'Gruvbox Dark'),
    ('gruvbox-light', 'Gruvbox Light'),
    ('hopscotch', 'Hopscotch'),
    ('hybrid', 'Hybrid'),
    ('idea', 'Idea'),
    ('ir-black', 'Ir Black'),
    ('isbl-editor-dark', 'Isbl Editor Dark'),
    ('isbl-editor-light', 'Isbl Editor Light'),
    ('kimbie.dark', 'Kimbie Dark'),
    ('kimbie.light', 'Kimbie Light'),
    ('lightfair', 'Lightfair'),
    ('magula', 'Magula'),
    ('mono-blue', 'Mono Blue'),
    ('monokai', 'Monokai Sublime'),
    ('monokai-sublime', 'Monokai'),
    ('nord', 'Nord'),
    ('obsidian', 'Obsidian'),
    ('ocean', 'Ocean'),
    ('paraiso-dark', 'Paraiso Dark'),
    ('paraiso-light', 'Paraiso Light'),
    ('pojoaque', 'Pojoaque'),
    ('purebasic', 'Purebasic'),
    ('qtcreator_dark', 'Qtcreator Dark'),
    ('qtcreator_light', 'Qtcreator Light'),
    ('railscasts', 'Railscasts'),
    ('rainbow', 'Rainbow'),
    ('routeros', 'Routeros'),
    ('school-book', 'School Book'),
    ('shades-of-purple', 'Shades Of Purple'),
    ('solarized-dark', 'Solarized Dark'),
    ('solarized-light', 'Solarized Light'),
    ('sunburst', 'Sunburst'),
    ('tomorrow', 'Tomorrow Night Blue'),
    ('tomorrow-night-blue', 'Tomorrow Night Bright'),
    ('tomorrow-night-bright', 'Tomorrow Night Eighties'),
    ('tomorrow-night', 'Tomorrow Night'),
    ('tomorrow-night-eighties', 'Tomorrow'),
    ('vs2015', 'Vs'),
    ('vs', 'Vs 2015'),
    ('xcode', 'Xcode'),
    ('xt256', 'Xt 256'),
    ('zenburn', 'Zenburn'),
)

HIGHLIGHT_THEMES = getattr(settings, 'HIGHLIGHT_THEMES', DEFAULT_THEMES)

DEFAULT_LANGUAGES = (
    ('1c', '1C'),
    ('accesslog', 'Access logs'),
    ('ada', 'Ada'),
    ('armasm', 'ARM assembler'),
    ('avrasm', 'AVR assembler'),
    ('actionscript', 'ActionScript'),
    ('apache', 'Apache'),
    ('applescript', 'AppleScript'),
    ('asciidoc', 'AsciiDoc'),
    ('aspectj', 'AspectJ'),
    ('autohotkey', 'AutoHotkey'),
    ('autoit', 'AutoIt'),
    ('axapta', 'Axapta'),
    ('bash', 'Bash'),
    ('basic', 'Basic'),
    ('bnf', 'BNF'),
    ('brainfuck', 'Brainfuck'),
    ('cs', 'C#'),
    ('cpp', 'C++'),
    ('cal', 'C/AL'),
    ('cos', 'Cache Object Script'),
    ('cmake', 'CMake'),
    ('csp', 'CSP'),
    ('css', 'CSS'),
    ('capnproto', 'Cap\'n Proto'),
    ('clojure', 'Clojure'),
    ('coffeescript', 'CoffeeScript'),
    ('crmsh', 'Crmsh'),
    ('crystal', 'Crystal'),
    ('d', 'D'),
    ('dns', 'DNS Zone file'),
    ('dos', 'DOS'),
    ('dart', 'Dart'),
    ('delphi', 'Delphi'),
    ('diff', 'Diff'),
    ('django', 'Django'),
    ('dockerfile', 'Dockerfile'),
    ('dts', 'DTS (Device Tree'),
    ('dust', 'Dust'),
    ('elixir', 'Elixir'),
    ('elm', 'Elm'),
    ('erlang', 'Erlang'),
    ('fsharp', 'F#'),
    ('fix', 'FIX'),
    ('fortran', 'Fortran'),
    ('gcode', 'G-Code'),
    ('gams', 'Gams'),
    ('gauss', 'GAUSS'),
    ('gherkin', 'Gherkin'),
    ('go', 'Go'),
    ('golo', 'Golo'),
    ('gradle', 'Gradle'),
    ('groovy', 'Groovy'),
    ('xml', 'HTML,XML'),
    ('http', 'HTTP'),
    ('haml', 'Haml'),
    ('handlebars', 'Handlebars'),
    ('haskell', 'Haskell'),
    ('haxe', 'Haxe'),
    ('ini', 'Ini'),
    ('inform7', 'Inform7'),
    ('irpf90', 'IRPF90'),
    ('json', 'JSON'),
    ('java', 'Java'),
    ('javascript', 'JavaScript'),
    ('lasso', 'Lasso'),
    ('less', 'Less'),
    ('lisp', 'Lisp'),
    ('livecodeserver', 'LiveCode Server'),
    ('livescript', 'LiveScript'),
    ('lua', 'Lua'),
    ('makefile', 'Makefile'),
    ('markdown', 'Markdown'),
    ('mathematica', 'Mathematica'),
    ('matlab', 'Matlab'),
    ('maxima', 'Maxima'),
    ('mel', 'Maya Embedded Language'),
    ('mercury', 'Mercury'),
    ('mizar', 'Mizar'),
    ('mojolicious', 'Mojolicious'),
    ('monkey', 'Monkey'),
    ('moonscript', 'Moonscript'),
    ('nsis', 'NSIS'),
    ('nginx', 'Nginx'),
    ('nimrod', 'Nimrod'),
    ('nix', 'Nix'),
    ('ocaml', 'OCaml'),
    ('C', 'Objective'),
    ('glsl', 'OpenGL Shading Language'),
    ('openscad', 'OpenSCAD'),
    ('ruleslanguage', 'Oracle Rules Language'),
    ('oxygene', 'Oxygene'),
    ('pf', 'PF'),
    ('php', 'PHP'),
    ('parser3', 'Parser3'),
    ('perl', 'Perl'),
    ('powershell', 'PowerShell'),
    ('processing', 'Processing'),
    ('prolog', 'Prolog'),
    ('protobuf', 'Protocol Buffers'),
    ('puppet', 'Puppet'),
    ('python', 'Python'),
    ('profile', 'Python profiler results'),
    ('k', 'Q'),
    ('qml', 'QML'),
    ('r', 'R'),
    ('rib', 'RenderMan RIB'),
    ('rsl', 'RenderMan RSL'),
    ('graph', 'Roboconf'),
    ('ruby', 'Ruby'),
    ('rust', 'Rust'),
    ('scss', 'SCSS'),
    ('sql', 'SQL'),
    ('p21', 'STEP Part 21'),
    ('scala', 'Scala'),
    ('scheme', 'Scheme'),
    ('scilab', 'Scilab'),
    ('smali', 'Smali'),
    ('smalltalk', 'Smalltalk'),
    ('stan', 'Stan'),
    ('stata', 'Stata'),
    ('stylus', 'Stylus'),
    ('swift', 'Swift'),
    ('tcl', 'Tcl'),
    ('tex', 'TeX'),
    ('thrift', 'Thrift'),
    ('tp', 'TP'),
    ('twig', 'Twig'),
    ('typescript', 'TypeScript'),
    ('vbnet', 'VB.Net'),
    ('vbscript', 'VBScript'),
    ('vhdl', 'VHDL'),
    ('vala', 'Vala'),
    ('verilog', 'Verilog'),
    ('Script', 'Vim'),
    ('x86asm', 'x86 Assembly'),
    ('xl', 'XL'),
    ('xpath', 'XQuery'),
    ('zephir', 'Zephir'),
)

HIGHLIGHT_LANGUAGES = getattr(settings, 'HIGHLIGHT_LANGUAGES',
                              DEFAULT_LANGUAGES)
